//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpdySvc.Service.HireService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseMessage", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SpdySvc.Service.HireService.BaseResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SpdySvc.Service.HireService.BaseRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SpdySvc.Service.HireService.PreHireRequest))]
    public partial class BaseMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountIdField, value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Common")]
    [System.SerializableAttribute()]
    public partial class BaseResponse : SpdySvc.Service.HireService.BaseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.HireService.ErrorDto ErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.HireService.ErrorDto Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRequest", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SpdySvc.Service.HireService.PreHireRequest))]
    public partial class BaseRequest : SpdySvc.Service.HireService.BaseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.HireService.AxaptaCompanyType AxaptaCompanyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.HireService.AxaptaCompanyType AxaptaCompany {
            get {
                return this.AxaptaCompanyField;
            }
            set {
                if ((this.AxaptaCompanyField.Equals(value) != true)) {
                    this.AxaptaCompanyField = value;
                    this.RaisePropertyChanged("AxaptaCompany");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreHireRequest", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.HireService")]
    [System.SerializableAttribute()]
    public partial class PreHireRequest : SpdySvc.Service.HireService.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.HireService.CardChargesDto CardChargesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerOrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.HireService.PersonDto DeliverToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryInstructionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepotDeliveryChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpectedOffHireDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OnHireDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.HireService.PersonDto OrderedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.HireService.RequestProductDto[] ProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RetailDeliveryChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebOrderNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.HireService.CardChargesDto CardCharges {
            get {
                return this.CardChargesField;
            }
            set {
                if ((object.ReferenceEquals(this.CardChargesField, value) != true)) {
                    this.CardChargesField = value;
                    this.RaisePropertyChanged("CardCharges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerOrderNumber {
            get {
                return this.CustomerOrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerOrderNumberField, value) != true)) {
                    this.CustomerOrderNumberField = value;
                    this.RaisePropertyChanged("CustomerOrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.HireService.PersonDto DeliverTo {
            get {
                return this.DeliverToField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliverToField, value) != true)) {
                    this.DeliverToField = value;
                    this.RaisePropertyChanged("DeliverTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryInstructions {
            get {
                return this.DeliveryInstructionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryInstructionsField, value) != true)) {
                    this.DeliveryInstructionsField = value;
                    this.RaisePropertyChanged("DeliveryInstructions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepotDeliveryCharge {
            get {
                return this.DepotDeliveryChargeField;
            }
            set {
                if ((object.ReferenceEquals(this.DepotDeliveryChargeField, value) != true)) {
                    this.DepotDeliveryChargeField = value;
                    this.RaisePropertyChanged("DepotDeliveryCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpectedOffHireDate {
            get {
                return this.ExpectedOffHireDateField;
            }
            set {
                if ((this.ExpectedOffHireDateField.Equals(value) != true)) {
                    this.ExpectedOffHireDateField = value;
                    this.RaisePropertyChanged("ExpectedOffHireDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OnHireDate {
            get {
                return this.OnHireDateField;
            }
            set {
                if ((this.OnHireDateField.Equals(value) != true)) {
                    this.OnHireDateField = value;
                    this.RaisePropertyChanged("OnHireDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.HireService.PersonDto OrderedBy {
            get {
                return this.OrderedByField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderedByField, value) != true)) {
                    this.OrderedByField = value;
                    this.RaisePropertyChanged("OrderedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.HireService.RequestProductDto[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RetailDeliveryCharge {
            get {
                return this.RetailDeliveryChargeField;
            }
            set {
                if ((object.ReferenceEquals(this.RetailDeliveryChargeField, value) != true)) {
                    this.RetailDeliveryChargeField = value;
                    this.RaisePropertyChanged("RetailDeliveryCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebOrderNumber {
            get {
                return this.WebOrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.WebOrderNumberField, value) != true)) {
                    this.WebOrderNumberField = value;
                    this.RaisePropertyChanged("WebOrderNumber");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AxaptaCompanyType", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Common")]
    public enum AxaptaCompanyType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SAS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BAS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DUB = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NIR = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SIR = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EGT = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OMA = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardChargesDto", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Common")]
    [System.SerializableAttribute()]
    public partial class CardChargesDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountChargedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApprovalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ApprovalDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AmountCharged {
            get {
                return this.AmountChargedField;
            }
            set {
                if ((this.AmountChargedField.Equals(value) != true)) {
                    this.AmountChargedField = value;
                    this.RaisePropertyChanged("AmountCharged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApprovalCode {
            get {
                return this.ApprovalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ApprovalCodeField, value) != true)) {
                    this.ApprovalCodeField = value;
                    this.RaisePropertyChanged("ApprovalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ApprovalDate {
            get {
                return this.ApprovalDateField;
            }
            set {
                if ((this.ApprovalDateField.Equals(value) != true)) {
                    this.ApprovalDateField = value;
                    this.RaisePropertyChanged("ApprovalDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonDto", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Common")]
    [System.SerializableAttribute()]
    public partial class PersonDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.HireService.AddressDto AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.HireService.ContactDetailsDto ContactDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.HireService.OptOutsDto OptOutsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.HireService.AddressDto Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.HireService.ContactDetailsDto ContactDetails {
            get {
                return this.ContactDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactDetailsField, value) != true)) {
                    this.ContactDetailsField = value;
                    this.RaisePropertyChanged("ContactDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.HireService.OptOutsDto OptOuts {
            get {
                return this.OptOutsField;
            }
            set {
                if ((object.ReferenceEquals(this.OptOutsField, value) != true)) {
                    this.OptOutsField = value;
                    this.RaisePropertyChanged("OptOuts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestProductDto", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Common")]
    [System.SerializableAttribute()]
    public partial class RequestProductDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FromDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<SpdySvc.Service.HireService.HireLineType> ProductIndicatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ToDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FromDate {
            get {
                return this.FromDateField;
            }
            set {
                if ((this.FromDateField.Equals(value) != true)) {
                    this.FromDateField = value;
                    this.RaisePropertyChanged("FromDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIdField, value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<SpdySvc.Service.HireService.HireLineType> ProductIndicator {
            get {
                return this.ProductIndicatorField;
            }
            set {
                if ((this.ProductIndicatorField.Equals(value) != true)) {
                    this.ProductIndicatorField = value;
                    this.RaisePropertyChanged("ProductIndicator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ToDate {
            get {
                return this.ToDateField;
            }
            set {
                if ((this.ToDateField.Equals(value) != true)) {
                    this.ToDateField = value;
                    this.RaisePropertyChanged("ToDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorDto", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Common")]
    [System.SerializableAttribute()]
    public partial class ErrorDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorText {
            get {
                return this.ErrorTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorTextField, value) != true)) {
                    this.ErrorTextField = value;
                    this.RaisePropertyChanged("ErrorText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressDto", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Common")]
    [System.SerializableAttribute()]
    public partial class AddressDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostcodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressName {
            get {
                return this.AddressNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressNameField, value) != true)) {
                    this.AddressNameField = value;
                    this.RaisePropertyChanged("AddressName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Postcode {
            get {
                return this.PostcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostcodeField, value) != true)) {
                    this.PostcodeField = value;
                    this.RaisePropertyChanged("Postcode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactDetailsDto", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Common")]
    [System.SerializableAttribute()]
    public partial class ContactDetailsDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaxNumber {
            get {
                return this.FaxNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxNumberField, value) != true)) {
                    this.FaxNumberField = value;
                    this.RaisePropertyChanged("FaxNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber {
            get {
                return this.MobileNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNumberField, value) != true)) {
                    this.MobileNumberField = value;
                    this.RaisePropertyChanged("MobileNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelephoneNumber {
            get {
                return this.TelephoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneNumberField, value) != true)) {
                    this.TelephoneNumberField = value;
                    this.RaisePropertyChanged("TelephoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OptOutsDto", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Common")]
    [System.SerializableAttribute()]
    public partial class OptOutsDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SMSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SelectedPartnersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ThirdPartyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Email {
            get {
                return this.EmailField;
            }
            set {
                if ((this.EmailField.Equals(value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Post {
            get {
                return this.PostField;
            }
            set {
                if ((this.PostField.Equals(value) != true)) {
                    this.PostField = value;
                    this.RaisePropertyChanged("Post");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SMS {
            get {
                return this.SMSField;
            }
            set {
                if ((this.SMSField.Equals(value) != true)) {
                    this.SMSField = value;
                    this.RaisePropertyChanged("SMS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SelectedPartners {
            get {
                return this.SelectedPartnersField;
            }
            set {
                if ((this.SelectedPartnersField.Equals(value) != true)) {
                    this.SelectedPartnersField = value;
                    this.RaisePropertyChanged("SelectedPartners");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((this.TelephoneField.Equals(value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ThirdParty {
            get {
                return this.ThirdPartyField;
            }
            set {
                if ((this.ThirdPartyField.Equals(value) != true)) {
                    this.ThirdPartyField = value;
                    this.RaisePropertyChanged("ThirdParty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HireLineType", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.HireService")]
    public enum HireLineType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SingleLine = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MainKitLine = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ComponentKitLine = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpeedyFault", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Exceptions")]
    [System.SerializableAttribute()]
    public partial class SpeedyFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.HireService.IHireService")]
    public interface IHireService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHireService/PlacePrehireRequest", ReplyAction="http://tempuri.org/IHireService/PlacePrehireRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SpdySvc.Service.HireService.SpeedyFault), Action="http://tempuri.org/IHireService/PlacePrehireRequestSpeedyFaultFault", Name="SpeedyFault", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Exceptions")]
        SpdySvc.Service.HireService.BaseResponse PlacePrehireRequest(SpdySvc.Service.HireService.PreHireRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHireService/PlacePrehireRequest", ReplyAction="http://tempuri.org/IHireService/PlacePrehireRequestResponse")]
        System.Threading.Tasks.Task<SpdySvc.Service.HireService.BaseResponse> PlacePrehireRequestAsync(SpdySvc.Service.HireService.PreHireRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHireServiceChannel : SpdySvc.Service.HireService.IHireService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HireServiceClient : System.ServiceModel.ClientBase<SpdySvc.Service.HireService.IHireService>, SpdySvc.Service.HireService.IHireService {
        
        public HireServiceClient() {
        }
        
        public HireServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HireServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HireServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HireServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SpdySvc.Service.HireService.BaseResponse PlacePrehireRequest(SpdySvc.Service.HireService.PreHireRequest request) {
            return base.Channel.PlacePrehireRequest(request);
        }
        
        public System.Threading.Tasks.Task<SpdySvc.Service.HireService.BaseResponse> PlacePrehireRequestAsync(SpdySvc.Service.HireService.PreHireRequest request) {
            return base.Channel.PlacePrehireRequestAsync(request);
        }
    }
}
