//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpdySvc.Service.PriceService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseMessage", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SpdySvc.Service.PriceService.BaseResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SpdySvc.Service.PriceService.PriceEnquiryDetailResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SpdySvc.Service.PriceService.PriceEnquirySummaryResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SpdySvc.Service.PriceService.BaseRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SpdySvc.Service.PriceService.PriceEnquiryRequest))]
    public partial class BaseMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountIdField, value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SpdySvc.Service.PriceService.PriceEnquiryDetailResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SpdySvc.Service.PriceService.PriceEnquirySummaryResponse))]
    public partial class BaseResponse : SpdySvc.Service.PriceService.BaseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.PriceService.ErrorDto ErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.PriceService.ErrorDto Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceEnquiryDetailResponse", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.PriceService")]
    [System.SerializableAttribute()]
    public partial class PriceEnquiryDetailResponse : SpdySvc.Service.PriceService.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.PriceService.AccountType AccountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.PriceService.CurrencyType CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DeliveryChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.PriceService.DetailProductDto[] DetailProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalBuyValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalBuyVatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalHireCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalHireDepositField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalHireValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalHireVatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalNetValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalPayableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalSpeedyShieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalSpeedyShieldVATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalVATField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.PriceService.AccountType AccountType {
            get {
                return this.AccountTypeField;
            }
            set {
                if ((this.AccountTypeField.Equals(value) != true)) {
                    this.AccountTypeField = value;
                    this.RaisePropertyChanged("AccountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.PriceService.CurrencyType Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((this.CurrencyField.Equals(value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DeliveryCharge {
            get {
                return this.DeliveryChargeField;
            }
            set {
                if ((this.DeliveryChargeField.Equals(value) != true)) {
                    this.DeliveryChargeField = value;
                    this.RaisePropertyChanged("DeliveryCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.PriceService.DetailProductDto[] DetailProducts {
            get {
                return this.DetailProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailProductsField, value) != true)) {
                    this.DetailProductsField = value;
                    this.RaisePropertyChanged("DetailProducts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalBuyValue {
            get {
                return this.TotalBuyValueField;
            }
            set {
                if ((this.TotalBuyValueField.Equals(value) != true)) {
                    this.TotalBuyValueField = value;
                    this.RaisePropertyChanged("TotalBuyValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalBuyVat {
            get {
                return this.TotalBuyVatField;
            }
            set {
                if ((this.TotalBuyVatField.Equals(value) != true)) {
                    this.TotalBuyVatField = value;
                    this.RaisePropertyChanged("TotalBuyVat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalHireCost {
            get {
                return this.TotalHireCostField;
            }
            set {
                if ((this.TotalHireCostField.Equals(value) != true)) {
                    this.TotalHireCostField = value;
                    this.RaisePropertyChanged("TotalHireCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalHireDeposit {
            get {
                return this.TotalHireDepositField;
            }
            set {
                if ((this.TotalHireDepositField.Equals(value) != true)) {
                    this.TotalHireDepositField = value;
                    this.RaisePropertyChanged("TotalHireDeposit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalHireValue {
            get {
                return this.TotalHireValueField;
            }
            set {
                if ((this.TotalHireValueField.Equals(value) != true)) {
                    this.TotalHireValueField = value;
                    this.RaisePropertyChanged("TotalHireValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalHireVat {
            get {
                return this.TotalHireVatField;
            }
            set {
                if ((this.TotalHireVatField.Equals(value) != true)) {
                    this.TotalHireVatField = value;
                    this.RaisePropertyChanged("TotalHireVat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalNetValue {
            get {
                return this.TotalNetValueField;
            }
            set {
                if ((this.TotalNetValueField.Equals(value) != true)) {
                    this.TotalNetValueField = value;
                    this.RaisePropertyChanged("TotalNetValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalPayable {
            get {
                return this.TotalPayableField;
            }
            set {
                if ((this.TotalPayableField.Equals(value) != true)) {
                    this.TotalPayableField = value;
                    this.RaisePropertyChanged("TotalPayable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalSpeedyShield {
            get {
                return this.TotalSpeedyShieldField;
            }
            set {
                if ((this.TotalSpeedyShieldField.Equals(value) != true)) {
                    this.TotalSpeedyShieldField = value;
                    this.RaisePropertyChanged("TotalSpeedyShield");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalSpeedyShieldVAT {
            get {
                return this.TotalSpeedyShieldVATField;
            }
            set {
                if ((this.TotalSpeedyShieldVATField.Equals(value) != true)) {
                    this.TotalSpeedyShieldVATField = value;
                    this.RaisePropertyChanged("TotalSpeedyShieldVAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalVAT {
            get {
                return this.TotalVATField;
            }
            set {
                if ((this.TotalVATField.Equals(value) != true)) {
                    this.TotalVATField = value;
                    this.RaisePropertyChanged("TotalVAT");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceEnquirySummaryResponse", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.PriceService")]
    [System.SerializableAttribute()]
    public partial class PriceEnquirySummaryResponse : SpdySvc.Service.PriceService.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.PriceService.CurrencyType CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.PriceService.SummaryProductDto[] ProductsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.PriceService.CurrencyType Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((this.CurrencyField.Equals(value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.PriceService.SummaryProductDto[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRequest", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SpdySvc.Service.PriceService.PriceEnquiryRequest))]
    public partial class BaseRequest : SpdySvc.Service.PriceService.BaseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.PriceService.AxaptaCompanyType AxaptaCompanyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.PriceService.AxaptaCompanyType AxaptaCompany {
            get {
                return this.AxaptaCompanyField;
            }
            set {
                if ((this.AxaptaCompanyField.Equals(value) != true)) {
                    this.AxaptaCompanyField = value;
                    this.RaisePropertyChanged("AxaptaCompany");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceEnquiryRequest", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.PriceService")]
    [System.SerializableAttribute()]
    public partial class PriceEnquiryRequest : SpdySvc.Service.PriceService.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.PriceService.CurrencyType CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DeliveryPreferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DisableSalesDeliveryChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FromDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.PriceService.RequestProductDto[] ProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ToDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.PriceService.CurrencyType Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((this.CurrencyField.Equals(value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeliveryPreference {
            get {
                return this.DeliveryPreferenceField;
            }
            set {
                if ((this.DeliveryPreferenceField.Equals(value) != true)) {
                    this.DeliveryPreferenceField = value;
                    this.RaisePropertyChanged("DeliveryPreference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DisableSalesDeliveryCharge {
            get {
                return this.DisableSalesDeliveryChargeField;
            }
            set {
                if ((this.DisableSalesDeliveryChargeField.Equals(value) != true)) {
                    this.DisableSalesDeliveryChargeField = value;
                    this.RaisePropertyChanged("DisableSalesDeliveryCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FromDate {
            get {
                return this.FromDateField;
            }
            set {
                if ((this.FromDateField.Equals(value) != true)) {
                    this.FromDateField = value;
                    this.RaisePropertyChanged("FromDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.PriceService.RequestProductDto[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ToDate {
            get {
                return this.ToDateField;
            }
            set {
                if ((this.ToDateField.Equals(value) != true)) {
                    this.ToDateField = value;
                    this.RaisePropertyChanged("ToDate");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AxaptaCompanyType", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Common")]
    public enum AxaptaCompanyType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SAS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BAS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DUB = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NIR = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SIR = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EGT = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OMA = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurrencyType", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Common")]
    public enum CurrencyType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GBP = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EUR = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestProductDto", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Common")]
    [System.SerializableAttribute()]
    public partial class RequestProductDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FromDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<SpdySvc.Service.PriceService.HireLineType> ProductIndicatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ToDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FromDate {
            get {
                return this.FromDateField;
            }
            set {
                if ((this.FromDateField.Equals(value) != true)) {
                    this.FromDateField = value;
                    this.RaisePropertyChanged("FromDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIdField, value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<SpdySvc.Service.PriceService.HireLineType> ProductIndicator {
            get {
                return this.ProductIndicatorField;
            }
            set {
                if ((this.ProductIndicatorField.Equals(value) != true)) {
                    this.ProductIndicatorField = value;
                    this.RaisePropertyChanged("ProductIndicator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ToDate {
            get {
                return this.ToDateField;
            }
            set {
                if ((this.ToDateField.Equals(value) != true)) {
                    this.ToDateField = value;
                    this.RaisePropertyChanged("ToDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorDto", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Common")]
    [System.SerializableAttribute()]
    public partial class ErrorDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorText {
            get {
                return this.ErrorTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorTextField, value) != true)) {
                    this.ErrorTextField = value;
                    this.RaisePropertyChanged("ErrorText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountType", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Common")]
    public enum AccountType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Credit = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAYG = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetailProductDto", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.PriceService")]
    [System.SerializableAttribute()]
    public partial class DetailProductDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.PriceService.PriceType PriceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.PriceService.RateType RateTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.PriceService.PriceType PriceType {
            get {
                return this.PriceTypeField;
            }
            set {
                if ((this.PriceTypeField.Equals(value) != true)) {
                    this.PriceTypeField = value;
                    this.RaisePropertyChanged("PriceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIdField, value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.PriceService.RateType RateType {
            get {
                return this.RateTypeField;
            }
            set {
                if ((this.RateTypeField.Equals(value) != true)) {
                    this.RateTypeField = value;
                    this.RaisePropertyChanged("RateType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceType", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.PriceService")]
    public enum PriceType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotAvailable = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnApplication = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Available = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RateType", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Common")]
    public enum RateType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OneDay = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TwoDays = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThreeDays = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Week = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Buy = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Loss = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sale = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MinimumWeek = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SummaryProductDto", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.PriceService")]
    [System.SerializableAttribute()]
    public partial class SummaryProductDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.PriceService.SummaryPriceDto BuyPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.PriceService.SummaryPriceDto DayRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.PriceService.SummaryPriceDto ExtraDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.PriceService.SummaryPriceDto MinimumWeekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.PriceService.SummaryPriceDto WeekRateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.PriceService.SummaryPriceDto BuyPrice {
            get {
                return this.BuyPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyPriceField, value) != true)) {
                    this.BuyPriceField = value;
                    this.RaisePropertyChanged("BuyPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.PriceService.SummaryPriceDto DayRate {
            get {
                return this.DayRateField;
            }
            set {
                if ((object.ReferenceEquals(this.DayRateField, value) != true)) {
                    this.DayRateField = value;
                    this.RaisePropertyChanged("DayRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.PriceService.SummaryPriceDto ExtraDay {
            get {
                return this.ExtraDayField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraDayField, value) != true)) {
                    this.ExtraDayField = value;
                    this.RaisePropertyChanged("ExtraDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.PriceService.SummaryPriceDto MinimumWeek {
            get {
                return this.MinimumWeekField;
            }
            set {
                if ((object.ReferenceEquals(this.MinimumWeekField, value) != true)) {
                    this.MinimumWeekField = value;
                    this.RaisePropertyChanged("MinimumWeek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIdField, value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.PriceService.SummaryPriceDto WeekRate {
            get {
                return this.WeekRateField;
            }
            set {
                if ((object.ReferenceEquals(this.WeekRateField, value) != true)) {
                    this.WeekRateField = value;
                    this.RaisePropertyChanged("WeekRate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SummaryPriceDto", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.PriceService")]
    [System.SerializableAttribute()]
    public partial class SummaryPriceDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpdySvc.Service.PriceService.PriceType PriceTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpdySvc.Service.PriceService.PriceType PriceType {
            get {
                return this.PriceTypeField;
            }
            set {
                if ((this.PriceTypeField.Equals(value) != true)) {
                    this.PriceTypeField = value;
                    this.RaisePropertyChanged("PriceType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HireLineType", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.HireService")]
    public enum HireLineType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SingleLine = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MainKitLine = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ComponentKitLine = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpeedyFault", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Exceptions")]
    [System.SerializableAttribute()]
    public partial class SpeedyFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.PriceService.IPriceService")]
    public interface IPriceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPriceService/GetHireRatesDetail", ReplyAction="http://tempuri.org/IPriceService/GetHireRatesDetailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SpdySvc.Service.PriceService.SpeedyFault), Action="http://tempuri.org/IPriceService/GetHireRatesDetailSpeedyFaultFault", Name="SpeedyFault", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Exceptions")]
        SpdySvc.Service.PriceService.PriceEnquiryDetailResponse GetHireRatesDetail(SpdySvc.Service.PriceService.PriceEnquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPriceService/GetHireRatesDetail", ReplyAction="http://tempuri.org/IPriceService/GetHireRatesDetailResponse")]
        System.Threading.Tasks.Task<SpdySvc.Service.PriceService.PriceEnquiryDetailResponse> GetHireRatesDetailAsync(SpdySvc.Service.PriceService.PriceEnquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPriceService/GetHireRatesSummary", ReplyAction="http://tempuri.org/IPriceService/GetHireRatesSummaryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SpdySvc.Service.PriceService.SpeedyFault), Action="http://tempuri.org/IPriceService/GetHireRatesSummarySpeedyFaultFault", Name="SpeedyFault", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Exceptions")]
        SpdySvc.Service.PriceService.PriceEnquirySummaryResponse GetHireRatesSummary(SpdySvc.Service.PriceService.PriceEnquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPriceService/GetHireRatesSummary", ReplyAction="http://tempuri.org/IPriceService/GetHireRatesSummaryResponse")]
        System.Threading.Tasks.Task<SpdySvc.Service.PriceService.PriceEnquirySummaryResponse> GetHireRatesSummaryAsync(SpdySvc.Service.PriceService.PriceEnquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPriceService/CanGetPriceFromAxapta", ReplyAction="http://tempuri.org/IPriceService/CanGetPriceFromAxaptaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SpdySvc.Service.PriceService.SpeedyFault), Action="http://tempuri.org/IPriceService/CanGetPriceFromAxaptaSpeedyFaultFault", Name="SpeedyFault", Namespace="http://schemas.datacontract.org/2004/07/Speedy.DataTransferObjects.Exceptions")]
        bool CanGetPriceFromAxapta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPriceService/CanGetPriceFromAxapta", ReplyAction="http://tempuri.org/IPriceService/CanGetPriceFromAxaptaResponse")]
        System.Threading.Tasks.Task<bool> CanGetPriceFromAxaptaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPriceServiceChannel : SpdySvc.Service.PriceService.IPriceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PriceServiceClient : System.ServiceModel.ClientBase<SpdySvc.Service.PriceService.IPriceService>, SpdySvc.Service.PriceService.IPriceService {
        
        public PriceServiceClient() {
        }
        
        public PriceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PriceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PriceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PriceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SpdySvc.Service.PriceService.PriceEnquiryDetailResponse GetHireRatesDetail(SpdySvc.Service.PriceService.PriceEnquiryRequest request) {
            return base.Channel.GetHireRatesDetail(request);
        }
        
        public System.Threading.Tasks.Task<SpdySvc.Service.PriceService.PriceEnquiryDetailResponse> GetHireRatesDetailAsync(SpdySvc.Service.PriceService.PriceEnquiryRequest request) {
            return base.Channel.GetHireRatesDetailAsync(request);
        }
        
        public SpdySvc.Service.PriceService.PriceEnquirySummaryResponse GetHireRatesSummary(SpdySvc.Service.PriceService.PriceEnquiryRequest request) {
            return base.Channel.GetHireRatesSummary(request);
        }
        
        public System.Threading.Tasks.Task<SpdySvc.Service.PriceService.PriceEnquirySummaryResponse> GetHireRatesSummaryAsync(SpdySvc.Service.PriceService.PriceEnquiryRequest request) {
            return base.Channel.GetHireRatesSummaryAsync(request);
        }
        
        public bool CanGetPriceFromAxapta() {
            return base.Channel.CanGetPriceFromAxapta();
        }
        
        public System.Threading.Tasks.Task<bool> CanGetPriceFromAxaptaAsync() {
            return base.Channel.CanGetPriceFromAxaptaAsync();
        }
    }
}
